# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WEIBO' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WEIBO

  target 'WEIBOUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'Alamofire', '~> 4.5'
  pod 'JZNavigationExtension',       '1.5.0.1'     #源码下载地址:https://github.com/JazysYu/JZNavigationExtension.git
#  pod 'HandyJSON'  ,                 '4.0.0-beta.1'       #源码下载地址:https://github.com/alibaba/handyjson
end
